version: '2'

networks:
  app-tier:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - app-tier
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=chess_repository_service
    networks:
      - app-tier
  php:
    image: bitnami/php-fpm:latest
    volumes:
      - ./..:/app
    ports:
      - 9000:9000
      - 443:8443
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=chess_repository_service
    depends_on:
      - mariadb
      - elasticsearch
    networks:
      - app-tier
  apache:
    image: rickynroses87/apache:latest
    ports:
      - 80:8080
    volumes:
      - ./vhost.conf:/vhosts/myapp.conf:ro
      - ./..:/app
    depends_on:
      - php
      - elasticsearch
    networks:
      - app-tier

volumes:
  elasticsearch-data-volume:
    driver: local
